quickstart_app_changelog:
    path:     /changelog
    defaults: { _controller: Quickstart\Bundle\AppBundle\Controller\DefaultController:changelogAction }

quickstart_app_homepage:
    path:     /
    defaults: { _controller: Quickstart\Bundle\AppBundle\Controller\DefaultController:indexAction }

quickstart_app_account:
    path:     /account
    defaults: { _controller: Quickstart\Bundle\AppBundle\Controller\AccountController:indexAction }
