quickstart_app_changelog:
    path:     /changelog
    defaults: { _controller: quickstart_app_default_controller:changelogAction }

quickstart_app_homepage:
    path:     /
    defaults: { _controller: quickstart_app_default_controller:indexAction }

quickstart_app_account:
    path:     /account
    defaults: { _controller: quickstart_app_account_controller:indexAction }
